# https://docs.codecov.com/docs/codecovyml-reference
# https://docs.codecov.com/docs/ignoring-paths#ignoring-a-specific-folder
ignore:
  - "tests"
# https://docs.codecov.com/docs/fixing-paths#how-to-provide-path-fixes-manually
fixes:
  - "/__w/::/home/runner/work/"
