
CREATE TABLE asteroid_respawn (
  asteroid INTEGER GENERATED ALWAYS AS IDENTITY,
  died_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  respawn_at TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (asteroid)
);

CREATE TABLE system_outpost_respawn (
  outpost INTEGER GENERATED ALWAYS AS IDENTITY,
  died_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  respawn_at TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (outpost)
);
