name: Build services

on:
  push:
    paths:
      - ".github/workflows/build-ci-docker-image.yml"
      - "build/ci/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  LIBPQXX_VERSION: 7.10.1
  CPP_VERSION: 20

jobs:
  extract-docker-tag:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract git commit hash
        id: docker-tag
        # https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
        run: echo "tag=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-24.04
    steps:
      build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: [extract-docker-tag]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/ci-cpp-build-image/Dockerfile
          # https://github.com/docker/build-push-action/issues/380
          build-args: |
            CPP_VERSION=$CPP_VERSION
            LIBPQXX_VERSION=$LIBPQXX_VERSION
          push: true
          tags: totocorpsoftwareinc/ci-cpp-build-image:${{ needs.extract-docker-tag.outputs.tag }}
