name: Build CI docker image

on:
  push:
    paths:
      - ".github/workflows/build-ci-docker-image.yml"
      - "build/ci-cpp-build-image/**"
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag to use for the image"
        required: false
        default: ""
      cpp_version:
        description: "C++ version to use"
        required: false
        default: "20"
      libpqxx_version:
        description: "Version of libpqxx to use"
        required: false
        default: "7.10.1"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CPP_VERSION: 20
  LIBPQXX_VERSION: 7.10.1

jobs:
  docker-props:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      tag: ${{ steps.docker-tag.outputs.tag }}
      cpp-version: ${{ steps.cpp-version.outputs.version }}
      libpqxx-version: ${{ steps.libpqxx-version.outputs.version }}
    steps:
      - uses: actions/checkout@v5
      - name: debug
        run: |
          echo ${{ github.event_name }}
      - name: Extract docker tag
        id: docker-tag
        # https://stackoverflow.com/questions/58886293/getting-current-branch-and-commit-hash-in-github-action
        run: |
          GIT_COMMIT_SHA=$(git rev-parse --short $GITHUB_SHA)
          TAG="${{ github.event.inputs.tag }}"
          if [ "$TAG" == "" ]; then
            TAG="$GIT_COMMIT_SHA"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Determine C++ version
        id: cpp-version
        run: |
          echo "version=${{ github.event.inputs.cpp_version || env.CPP_VERSION }}" >> $GITHUB_OUTPUT
      - name: Determine libpqxx version
        id: libpqxx-version
        run: |
          echo "version=${{ github.event.inputs.libpqxx_version || env.LIBPQXX_VERSION }}" >> $GITHUB_OUTPUT

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: [docker-props]
    steps:
      - uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/ci-cpp-build-image/Dockerfile
          # https://github.com/docker/build-push-action/issues/380
          build-args: |
            CPP_VERSION=${{ needs.docker-props.outputs.cpp-version }}
            LIBPQXX_VERSION=${{ needs.docker-props.outputs.libpqxx-version }}
          push: true
          tags: totocorpsoftwareinc/ci-cpp-build-image:${{ needs.docker-props.outputs.tag }}
