name: Clean GitHub actions cache for branch

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          echo "base ref: ${{ github.base_ref }}"
          echo "head ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"
          echo "ref name: ${{ github.ref_name }}"
