name: Clean GitHub actions cache for branch

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges
on:
  pull_request:
    types:
      - closed

jobs:
  clean-action-cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Debug
        run: |
          echo The PR was merged
          echo "base ref: ${{ github.base_ref }}"
          echo "head ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"
          echo "ref name: ${{ github.ref_name }}"
          echo "branch: refs/pull/${{ github.event.pull_request.number }}/merge"
      - name: Clean cache
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
        run: |
          echo "Fetching list of cache keys"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

          echo "Found $(echo "$cacheKeysForPR" | wc -l) cache keys to delete for branch $BRANCH"

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e

          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
            gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/heads/${{ github.head_ref }}
